auth_enabled: false

server:
  http_listen_port: 3100
  log_level: error

ingester:
  wal:
    dir: "/tmp/wal"
  lifecycler:
    address: "0.0.0.0"
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

memberlist:
  bind_addr:
    - "0.0.0.0"
  bind_port: 7946            # ← was a list, now a single integer
  join_members:
    - "loki:7946"

schema_config:
  configs:
    - from: 2022-11-20
      store: boltdb
      object_store: filesystem
      schema: v9
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  # (your existing chunk_store settings)

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
